apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: ingress-nginx-controller-metrics
  labels:
    app: ingress-nginx
    release: prometheus-operator
spec:
  endpoints:
  - interval: 10s
    port: metrics
  selector:
    matchLabels:
      app: ingress-nginx
  namespaceSelector:
    matchNames:
    - ingress-nginx